FROM node:20-alpine AS base 

FROM base AS deps 

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci 


FROM base AS build

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

ENV NEXT_TELMETRY_DISABLED=1

RUN npm run build:docker

FROM base AS runner

WORKDIR /app

ENV NEXT_TELMETRY_DISABLED=1

ENV NODE_ENV=dev
COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next
COPY --from=deps /app/package.json .
COPY --from=build /app/node_modules ./node_modules

CMD [ "npm","start" ]